version: '3'

tasks:
  build:
    cmds:
      - go build .

  docker:build:
    cmds:
      - docker buildx build --platform=linux/amd64,linux/arm64 -t hjr265/mghsiac:latest {{if .PUSH}}--push{{end}} .
